name: DevSecOps Pipeline (Cloud)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: '20'
      - run: npm install --ignore-scripts
      - run: npm test
      - name: Sauvegarder la couverture
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: coverage
          path: coverage/

  sonar-check:
    needs: unit-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Recuperer la couverture
        uses: actions/download-artifact@fa0a91b85d4f404e444306234a0fcdee9a14e4b7
        with:
          name: coverage
          path: coverage/
      - name: Analyse SonarQube Cloud
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true

  dependency-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Scan des dependances
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

  build-image:
    needs: [ sonar-check, dependency-scan ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Build de l'image
        run: docker build -t my-app:${{ github.sha }} .
      - name: Exporter l'image
        run: docker save my-app:${{ github.sha }} -o my-image.tar
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: docker-image
          path: my-image.tar

  container-scan:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444306234a0fcdee9a14e4b7
        with:
          name: docker-image
          path: .
      - name: Charger l'image
        run: docker load -i my-image.tar
      - name: Scan de l'image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'my-app:${{ github.sha }}'
          severity: 'CRITICAL'
          exit-code: '1'
